language: python
python:
  - "3.6"
# command to install dependencies
os:
  - linux
before_install:
  - sudo apt-get install python-tk
install:
  - pip3 install -r requirements.txt
  - pip3 install coverage
script:
  - coverage run Sample_Test_Folder/test.py
  - coverage run Sample_Test_Folder/testStandAlone.py
after_success:
  - codecov
branches:
  only:
    - master