language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
os:
  - linux
  - osx
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install python-tk ; fi
install:
  - pip3 install -r requirements.txt
script:
  - python3 Sample_Test_Folder/test.py
  - python3 Sample_Test_Folder/testStandAlone.py
branches:
  only:
    - master