language: python
python:
  - "3.6"
# command to install dependencies
os:
  - linux
before_install:
  - sudo apt-get install python-tk
install:
  - pip3 install -r requirements.txt
script:
  #- python3 Sample_Test_Folder/test.py
  - python3 Sample_Test_Folder/testStandAlone.py
branches:
  only:
    - master