language: python
notifications:
  email: false
python:
  - "3.6"
os:
  - linux
install:
  - pip3 install -r requirements.txt
  - pip3 install codecov
  - pip3 install coverage>=4.4.0
  - pip3 install pytest>=3.6.0
  - pip3 install pytest-cov
  - pip3 install Pillow
script:
  - coverage run tests/test.py
after_success:
  - coverage combine
  - coverage xml
  - codecov
branches:
    - master
    - tito