language: python
notifications:
  email: false
python:
  - "3.6"
os:
  - linux
before_install:
  - sudo apt-get install python-tk
install:
  - pip3 install -r requirements.txt
  - pip3 install codecov
  - pip3 install coverage>=4.4.0
  - pip3 install pytest>=3.6.0
  - pip3 install pytest-cov
script:
  - coverage run tests/test.py
  - coverage run tests/testStandAlone.py
after_success:
  - coverage combine
  - codecov
branches:
  only:
    - master